dist: bionic
language: python
python:
  - "3.8.0"

services:
  - docker

jobs:
  include:
    - stage: Release
      if: type != pull_request AND tag IS present
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - VERSION="${TRAVIS_TAG}" make build
      - VERSION="${TRAVIS_TAG}" make release
      - VERSION="${TRAVIS_TAG}" make tag_latest
      - VERSION="${TRAVIS_TAG}" make release_latest
      - VERSION="${TRAVIS_TAG}" make tag_version
      - VERSION="${TRAVIS_TAG}" make release_version